#!/bin/sh
set -e

# Run devcontainer feature tests with automatic cleanup of Docker artifacts.
# Test images match 'vsc-<digits>-*' and test volumes contain a numeric
# workspace folder basename (from the test framework's temp directories),
# so real devcontainer resources are never removed.
#
# Usage:
#   ./test.sh [options] [-- <devcontainer features test args>]
#
# Options:
#   --preserve    Skip cleanup of Docker images and volumes after tests
#   -h, --help    Show this help message
#
# Examples:
#   ./test.sh -- -f claude-code --skip-autogenerated --skip-duplicated
#   ./test.sh --preserve -- -f mise

PRESERVE=false

while [ $# -gt 0 ]; do
    case "$1" in
        --preserve)
            PRESERVE=true
            shift
            ;;
        -h|--help)
            sed -n '3,/^$/p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *)
            break
            ;;
    esac
done

# Run tests, capturing exit code
TEST_EXIT=0
devcontainer features test "$@" || TEST_EXIT=$?

if [ "$PRESERVE" = false ]; then
    echo "Cleaning up test Docker images..."
    # Test images are named vsc-<timestamp>-<hash>-features
    # Collect names first to avoid pipe-subshell issues with docker commands
    TEST_IMAGES=$(docker images --format '{{.Repository}}' | grep '^vsc-[0-9]' | sort -u || true)
    for img in $TEST_IMAGES; do
        echo "  Removing image: $img"
        # Retry once after a brief wait — container cleanup may not have fully released the image
        docker rmi "$img" 2>/dev/null || { sleep 2 && docker rmi "$img" 2>/dev/null; } || true
    done

    echo "Cleaning up test Docker volumes..."
    # Test volumes have a numeric workspace folder basename (timestamp) from
    # the test framework's temp directories, e.g. claude-code-config-1772046277784-<hash>.
    # Real devcontainer volumes use the project name instead, e.g. claude-code-config-my-app-<hash>.
    TEST_VOLUMES=$(docker volume ls --format '{{.Name}}' | grep -E '^[a-z].*-[0-9]{10,}-' || true)
    for vol in $TEST_VOLUMES; do
        echo "  Removing volume: $vol"
        docker volume rm "$vol" 2>/dev/null || true
    done

    echo "Cleanup complete."
else
    echo "Preserving test Docker images and volumes (--preserve)."
fi

exit "$TEST_EXIT"
